# Generated by Django 6.0.3 on 2026-03-10 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeteIslamique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nom_wolof', models.CharField(blank=True, max_length=100)),
                ('mois_hijri', models.IntegerField()),
                ('jour_hijri', models.IntegerField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Fête islamique',
                'ordering': ['mois_hijri', 'jour_hijri'],
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('type_event', models.CharField(choices=[('islamique', 'Islamique'), ('wolof', 'Wolof'), ('personnel', 'Personnel'), ('national', 'National')], default='personnel', max_length=20)),
                ('est_public', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
